Style/CaseEquality:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolProc:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: always_braces

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/InvertibleUnlessCondition:
  Enabled: true

Style/Lambda:
  EnforcedStyle: literal

Style/ParenthesesAroundCondition:
  AllowInMultilineConditions: true

Style/NegatedIf:
  Enabled: false

# lol

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/CaseLikeIf:
  Enabled: false

Style/MultipleComparison:
  Enabled: false
